import assert from "node:assert/strict";
import fs from "node:fs";
import test from "node:test";

const html = fs.readFileSync(new URL("./index.html", import.meta.url), "utf8");

test("mission page pay CTAs are visible and point at live $42 store rails", () => {
  assert.match(html, /--accent\s*:/);
  assert.doesNotMatch(html, /starts at \$3/);
  assert.doesNotMatch(html, /from \$3/);
  assert.match(html, /href="https:\/\/store\.3labs\.io"/);
  assert.match(html, /agentic-ai-governance-pack\?wanted=true/);
  assert.match(html, /tip-jar\?wanted=true/);
  assert.match(html, /Browse the store/);
  assert.match(html, /Pay \$42 with card/);
  assert.match(html, /fieldproofhq\.github\.io\/pay\//);
  assert.match(html, /buy\.stripe\.com\/eVq4gA91U3Rr1Yt6z31sQ00/);
  assert.match(html, /fractional-cmo-launch-kit\?wanted=true/);
  assert.match(html, /csuite\/cmo/);
  assert.doesNotMatch(html, /Self-buys do not count/i);
  assert.match(html, /background:var\(--accent\)/);
  const reference = fs.readFileSync(new URL("./agent-governance-reference.html", import.meta.url), "utf8");
  assert.match(reference, /buy\.stripe\.com\/eVq4gA91U3Rr1Yt6z31sQ00/);
  const pay = fs.readFileSync(new URL("./pay/index.html", import.meta.url), "utf8");
  assert.match(pay, /Pay \$42 with card/);
  assert.match(pay, /buy\.stripe\.com\/eVq4gA91U3Rr1Yt6z31sQ00/);
  assert.match(pay, /create-qr-code/);
  assert.match(pay, /Affirm/);
  assert.match(pay, /rel="payment"/);
  assert.match(pay, /application\/ld\+json/);
  assert.match(pay, /"price":"42.00"/);
  assert.match(pay, /og:url/);
  assert.doesNotMatch(pay, /Self-buys do not count/i);
  assert.match(html, /rel="payment"/);
  const llms = fs.readFileSync(new URL("./llms.txt", import.meta.url), "utf8");
  assert.match(llms, /buy\.stripe\.com\/eVq4gA91U3Rr1Yt6z31sQ00/);
  assert.match(llms, /fieldproofhq\.github\.io\/pay\//);
  const payWellKnown = JSON.parse(fs.readFileSync(new URL("./.well-known/pay", import.meta.url), "utf8"));
  assert.equal(payWellKnown.price_usd, 42);
  assert.equal(payWellKnown.url, "https://buy.stripe.com/eVq4gA91U3Rr1Yt6z31sQ00");
  assert.ok(payWellKnown.methods.includes("affirm"));
  const robots = fs.readFileSync(new URL("./robots.txt", import.meta.url), "utf8");
  assert.match(robots, /Sitemap: https:\/\/fieldproofhq\.github\.io\/sitemap\.xml/);
  const sitemap = fs.readFileSync(new URL("./sitemap.xml", import.meta.url), "utf8");
  assert.match(sitemap, /fieldproofhq\.github\.io\/pay\//);
  assert.match(sitemap, /buy\.stripe\.com\/eVq4gA91U3Rr1Yt6z31sQ00/);
  assert.match(sitemap, /policy-gate\.3labsio\.workers\.dev\/v1\/sponsor/);
});
