import assert from "node:assert/strict";
import fs from "node:fs";
import test from "node:test";

const html = fs.readFileSync(new URL("./index.html", import.meta.url), "utf8");

test("mission page pay CTAs are visible and point at live $42 store rails", () => {
  assert.match(html, /--accent\s*:/);
  assert.doesNotMatch(html, /starts at \$3/);
  assert.doesNotMatch(html, /from \$3/);
  assert.match(html, /href="https:\/\/store\.3labs\.io"/);
  assert.match(html, /agentic-ai-governance-pack\?wanted=true/);
  assert.match(html, /tip-jar\?wanted=true/);
  assert.match(html, /Browse the store/);
  assert.match(html, /Pay \$42 with card/);
  assert.match(html, /class="cta" href="https:\/\/fieldproofhq\.github\.io\/offer\/">Pay \$42/);
  assert.match(html, /fieldproofhq\.github\.io\/pay\//);
  assert.match(html, /buy\.stripe\.com\/eVq4gA91U3Rr1Yt6z31sQ00/);
  assert.match(html, /fractional-cmo-launch-kit\?wanted=true/);
  assert.match(html, /csuite\/cmo/);
  assert.doesNotMatch(html, /Self-buys do not count/i);
  assert.match(html, /background:var\(--accent\)/);
  const reference = fs.readFileSync(new URL("./agent-governance-reference.html", import.meta.url), "utf8");
  assert.match(reference, /buy\.stripe\.com\/eVq4gA91U3Rr1Yt6z31sQ00/);
  const pay = fs.readFileSync(new URL("./pay/index.html", import.meta.url), "utf8");
  assert.match(pay, /Pay \$42 with card/);
  assert.match(pay, /buy\.stripe\.com\/eVq4gA91U3Rr1Yt6z31sQ00/);
  assert.match(pay, /create-qr-code/);
  assert.match(pay, /Affirm/);
  assert.match(pay, /rel="payment"/);
  assert.match(pay, /application\/ld\+json/);
  assert.match(pay, /"price":"42.00"/);
  assert.match(pay, /og:url/);
  assert.doesNotMatch(pay, /Self-buys do not count/i);
  assert.match(html, /rel="payment"/);
  const llms = fs.readFileSync(new URL("./llms.txt", import.meta.url), "utf8");
  assert.match(llms, /buy\.stripe\.com\/eVq4gA91U3Rr1Yt6z31sQ00/);
  assert.match(llms, /fieldproofhq\.github\.io\/pay\//);
  const payWellKnown = JSON.parse(fs.readFileSync(new URL("./.well-known/pay", import.meta.url), "utf8"));
  assert.equal(payWellKnown.price_usd, 42);
  assert.equal(payWellKnown.url, "https://buy.stripe.com/eVq4gA91U3Rr1Yt6z31sQ00");
  assert.ok(payWellKnown.methods.includes("affirm"));
  const robots = fs.readFileSync(new URL("./robots.txt", import.meta.url), "utf8");
  assert.match(robots, /Sitemap: https:\/\/fieldproofhq\.github\.io\/sitemap\.xml/);
  const sitemap = fs.readFileSync(new URL("./sitemap.xml", import.meta.url), "utf8");
  assert.match(sitemap, /fieldproofhq\.github\.io\/pay\//);
  assert.match(sitemap, /fieldproofhq\.github\.io\/offer\//);
  const offer = fs.readFileSync(new URL("./offer/index.html", import.meta.url), "utf8");
  assert.match(offer, /buy\.stripe\.com\/eVq4gA91U3Rr1Yt6z31sQ00/);
  assert.match(offer, /rel="payment"/);
  assert.match(offer, /http-equiv="refresh"/);
  assert.match(offer, /location\.replace/);
  assert.match(offer, /application\/ld\+json/);
  assert.match(offer, /"price":"42.00"/);
  assert.doesNotMatch(offer, /Self-buys do not count/i);
  assert.match(sitemap, /buy\.stripe\.com\/eVq4gA91U3Rr1Yt6z31sQ00/);
  assert.match(sitemap, /policy-gate\.3labsio\.workers\.dev\/v1\/sponsor/);
  assert.match(sitemap, /fieldproofhq\.github\.io\/\.well-known\/agent-card\.json/);
  assert.match(sitemap, /fieldproofhq\.github\.io\/openapi\.json/);
  const agentCard = JSON.parse(fs.readFileSync(new URL("./.well-known/agent-card.json", import.meta.url), "utf8"));
  assert.equal(agentCard.card, "https://buy.stripe.com/eVq4gA91U3Rr1Yt6z31sQ00");
  assert.ok(agentCard.skills.some((s) => s.id === "pay-42"));
  const agentLegacy = JSON.parse(fs.readFileSync(new URL("./.well-known/agent.json", import.meta.url), "utf8"));
  assert.equal(agentLegacy.card, agentCard.card);
  const openapi = JSON.parse(fs.readFileSync(new URL("./openapi.json", import.meta.url), "utf8"));
  assert.equal(openapi.openapi, "3.1.0");
  assert.equal(openapi.externalDocs.url, agentCard.card);
  assert.ok(openapi.paths["/v1/sponsor"].post);
  const openapiWellKnown = JSON.parse(fs.readFileSync(new URL("./.well-known/openapi.json", import.meta.url), "utf8"));
  assert.equal(openapiWellKnown.externalDocs.url, agentCard.card);
  const x402 = JSON.parse(fs.readFileSync(new URL("./.well-known/x402", import.meta.url), "utf8"));
  assert.equal(x402.x402Version, 2);
  assert.equal(x402.fallback.url, "https://buy.stripe.com/eVq4gA91U3Rr1Yt6z31sQ00");
  const sponsor = x402.resources.find((r) => r.url.endsWith("/v1/sponsor"));
  assert.ok(sponsor);
  assert.equal(sponsor.accepts[0].amount, "42000000");
  assert.equal(sponsor.accepts[0].payTo, "0x07C2383008a9ed30581f27Db5531E19411c94fb3");
  assert.match(sitemap, /fieldproofhq\.github\.io\/\.well-known\/x402/);
  const plugin = JSON.parse(fs.readFileSync(new URL("./.well-known/ai-plugin.json", import.meta.url), "utf8"));
  assert.equal(plugin.schema_version, "v1");
  assert.equal(plugin.auth.type, "none");
  assert.equal(plugin["x-payment"].url, "https://buy.stripe.com/eVq4gA91U3Rr1Yt6z31sQ00");
  assert.match(plugin.api.url, /openapi\.json$/);
  assert.match(sitemap, /fieldproofhq\.github\.io\/\.well-known\/ai-plugin\.json/);
  const mcp = JSON.parse(fs.readFileSync(new URL("./.well-known/mcp.json", import.meta.url), "utf8"));
  assert.equal(mcp.transport, "streamable-http");
  assert.match(mcp.url, /policy-gate\.3labsio\.workers\.dev\/mcp$/);
  assert.ok(mcp.tools.includes("first_42_sponsor"));
  assert.equal(mcp.payment.url, "https://buy.stripe.com/eVq4gA91U3Rr1Yt6z31sQ00");
  assert.equal(mcp.invoice, "https://policy-gate.3labsio.workers.dev/v1/invoice");
  assert.equal(mcp.card_uri, "https://policy-gate.3labsio.workers.dev/v1/pay/card.uri");
  assert.equal(mcp.usdc_uri, "https://policy-gate.3labsio.workers.dev/v1/pay/usdc.uri");
  assert.equal(mcp.btc_uri, "https://policy-gate.3labsio.workers.dev/v1/pay/btc.uri");
  assert.match(sitemap, /fieldproofhq\.github\.io\/\.well-known\/mcp\.json/);
  const wellKnownLlms = fs.readFileSync(new URL("./.well-known/llms.txt", import.meta.url), "utf8");
  assert.match(wellKnownLlms, /buy\.stripe\.com\/eVq4gA91U3Rr1Yt6z31sQ00/);
  assert.match(wellKnownLlms, /policy-gate\.3labsio\.workers\.dev\/v1\/offer/);
  assert.match(sitemap, /fieldproofhq\.github\.io\/\.well-known\/llms\.txt/);
  assert.match(sitemap, /policy-gate\.3labsio\.workers\.dev\/v1\/offer/);
  const llmsFull = fs.readFileSync(new URL("./llms-full.txt", import.meta.url), "utf8");
  assert.match(llmsFull, /buy\.stripe\.com\/eVq4gA91U3Rr1Yt6z31sQ00/);
  assert.match(llmsFull, /fieldproofhq\.github\.io\/offer\//);
  assert.match(llmsFull, /policy-gate\.3labsio\.workers\.dev\/v1\/offer/);
  assert.match(llmsFull, /3labsio@gmail.com/);
  assert.match(llmsFull, /\/v1\/pay\/usdc\.uri/);
  assert.match(llmsFull, /\/v1\/pay\/btc\.uri/);
  assert.match(llmsFull, /\/v1\/invoice/);
  assert.match(llmsFull, /policy-gate\.3labsio\.workers\.dev\/mcp/);
  assert.match(llmsFull, /\/skills\/pay\/SKILL\.md/);
  const skill = fs.readFileSync(new URL("./skills/pay/SKILL.md", import.meta.url), "utf8");
  assert.match(skill, /name: fieldproof-pay-42/);
  assert.match(skill, /buy\.stripe\.com\/eVq4gA91U3Rr1Yt6z31sQ00/);
  assert.match(skill, /\/v1\/pay\/card\.uri/);
  assert.match(skill, /\/v1\/invoice/);
  assert.doesNotMatch(skill, /Self-buys do not count/i);
  const skillsDoc = JSON.parse(fs.readFileSync(new URL("./.well-known/skills.json", import.meta.url), "utf8"));
  assert.equal(skillsDoc.skills[0].amountUsd, 42);
  assert.equal(skillsDoc.skills[0].card, "https://buy.stripe.com/eVq4gA91U3Rr1Yt6z31sQ00");
  assert.ok(openapi.paths["/skills/pay/SKILL.md"].get);
  assert.equal(payWellKnown.also.skill, "https://policy-gate.3labsio.workers.dev/skills/pay/SKILL.md");
  assert.match(sitemap, /skills\/pay\/SKILL\.md/);
  const ghPkg = JSON.parse(fs.readFileSync(new URL("./package.json", import.meta.url), "utf8"));
  assert.ok(ghPkg.funding.some((item) => item.url === "https://buy.stripe.com/eVq4gA91U3Rr1Yt6z31sQ00"));
  assert.ok(ghPkg.funding.some((item) => /fieldproofhq\.github\.io\/offer\//.test(item.url)));
  assert.equal(payWellKnown.also.funding, "https://policy-gate.3labsio.workers.dev/package.json");
  assert.ok(openapi.paths["/package.json"].get);
  assert.match(llmsFull, /\/package\.json/);
  assert.match(sitemap, /policy-gate\.3labsio\.workers\.dev\/package\.json/);
  const zelleUri = fs.readFileSync(new URL("./pay/zelle.uri", import.meta.url), "utf8").trim();
  assert.match(zelleUri, /^mailto:3labsio@gmail.com\?subject=Fieldproof/);
  assert.equal(payWellKnown.also.zelle_uri, "https://policy-gate.3labsio.workers.dev/v1/pay/zelle.uri");
  assert.ok(openapi.paths["/v1/pay/zelle.uri"].get);
  assert.match(llmsFull, /\/v1\/pay\/zelle\.uri/);
  assert.match(sitemap, /policy-gate\.3labsio\.workers\.dev\/v1\/pay\/zelle\.uri/);
  const packUri = fs.readFileSync(new URL("./pay/pack.uri", import.meta.url), "utf8").trim();
  assert.equal(packUri, "https://store.3labs.io/l/agentic-ai-governance-pack?wanted=true");
  assert.equal(payWellKnown.also.pack_uri, "https://policy-gate.3labsio.workers.dev/v1/pay/pack.uri");
  assert.ok(openapi.paths["/v1/pay/pack.uri"].get);
  assert.match(llmsFull, /\/v1\/pay\/pack\.uri/);
  assert.match(sitemap, /policy-gate\.3labsio\.workers\.dev\/v1\/pay\/pack\.uri/);
  const tipUri = fs.readFileSync(new URL("./pay/tip-jar.uri", import.meta.url), "utf8").trim();
  assert.equal(tipUri, "https://store.3labs.io/l/tip-jar?wanted=true");
  assert.equal(payWellKnown.also.tip_uri, "https://policy-gate.3labsio.workers.dev/v1/pay/tip-jar.uri");
  assert.ok(openapi.paths["/v1/pay/tip-jar.uri"].get);
  assert.match(llmsFull, /\/v1\/pay\/tip-jar\.uri/);
  assert.match(sitemap, /policy-gate\.3labsio\.workers\.dev\/v1\/pay\/tip-jar\.uri/);
  const security = fs.readFileSync(new URL("./.well-known/security.txt", import.meta.url), "utf8");
  assert.match(security, /Contact: mailto:3labsio@gmail.com/);
  assert.match(security, /buy\.stripe\.com\/eVq4gA91U3Rr1Yt6z31sQ00/);
  assert.match(security, /\/v1\/invoice/);
  assert.equal(payWellKnown.also.security, "https://policy-gate.3labsio.workers.dev/.well-known/security.txt");
  assert.ok(openapi.paths["/.well-known/security.txt"].get);
  assert.match(llmsFull, /\/\.well-known\/security\.txt/);
  assert.match(sitemap, /fieldproofhq\.github\.io\/\.well-known\/security\.txt/);
  const humans = fs.readFileSync(new URL("./humans.txt", import.meta.url), "utf8");
  assert.match(humans, /\/\* TEAM \*\//);
  assert.match(humans, /3labsio@gmail.com/);
  assert.match(humans, /buy\.stripe\.com\/eVq4gA91U3Rr1Yt6z31sQ00/);
  assert.match(humans, /\/v1\/invoice/);
  assert.equal(payWellKnown.also.humans, "https://policy-gate.3labsio.workers.dev/humans.txt");
  assert.ok(openapi.paths["/humans.txt"].get);
  assert.match(llmsFull, /\/humans\.txt/);
  assert.match(sitemap, /fieldproofhq\.github\.io\/humans\.txt/);
  assert.match(llmsFull, /\/v1\/pay\/card\.uri/);
  const cardUri = fs.readFileSync(new URL("./pay/card.uri", import.meta.url), "utf8").trim();
  assert.equal(cardUri, "https://buy.stripe.com/eVq4gA91U3Rr1Yt6z31sQ00");
  assert.equal(payWellKnown.also.card_uri, "https://policy-gate.3labsio.workers.dev/v1/pay/card.uri");
  assert.ok(openapi.paths["/v1/pay/card.uri"].get);
  assert.match(sitemap, /policy-gate\.3labsio\.workers\.dev\/v1\/pay\/card\.uri/);
  const invoiceDoc = JSON.parse(fs.readFileSync(new URL("./invoice.json", import.meta.url), "utf8"));
  assert.equal(invoiceDoc.amountUsd, 42);
  assert.equal(invoiceDoc.card, "https://buy.stripe.com/eVq4gA91U3Rr1Yt6z31sQ00");
  assert.ok(invoiceDoc.methods.some((m) => m.scheme === "eip681" && /uint256=42000000/.test(m.uri)));
  assert.equal(payWellKnown.also.invoice, "https://policy-gate.3labsio.workers.dev/v1/invoice");
  assert.ok(openapi.paths["/v1/invoice"].get);
  assert.match(sitemap, /policy-gate\.3labsio\.workers\.dev\/v1\/invoice/);
  assert.match(sitemap, /fieldproofhq\.github\.io\/llms-full\.txt/);
  assert.match(sitemap, /policy-gate\.3labsio\.workers\.dev\/v1\/pay\/usdc\.uri/);
  assert.match(sitemap, /policy-gate\.3labsio\.workers\.dev\/v1\/pay\/btc\.uri/);
  const usdcUri = fs.readFileSync(new URL("./pay/usdc.uri", import.meta.url), "utf8").trim();
  assert.equal(usdcUri, "ethereum:0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913@8453/transfer?address=0x07C2383008a9ed30581f27Db5531E19411c94fb3&uint256=42000000");
  assert.equal(payWellKnown.also.usdc_uri, "https://policy-gate.3labsio.workers.dev/v1/pay/usdc.uri");
  assert.equal(payWellKnown.also.btc_uri, "https://policy-gate.3labsio.workers.dev/v1/pay/btc.uri");
  assert.ok(openapi.paths["/v1/pay/usdc.uri"].get);
  assert.ok(openapi.paths["/v1/pay/btc.uri"].get);
  const funding = fs.readFileSync(new URL("./.github/FUNDING.yml", import.meta.url), "utf8");
  assert.match(funding, /fieldproofhq\.github\.io\/offer\//);
  assert.match(funding, /buy\.stripe\.com\/eVq4gA91U3Rr1Yt6z31sQ00/);
});
